framework:
  - terraform
download-external-modules: true
evaluate-variables: true
compact: true
quiet: true

# Skip specific checks that might not be relevant for this demo
skip-check:
  - CKV_AWS_79   # Ensure Instance Metadata Service Version 1 is not enabled
  - CKV_AWS_8    # Ensure all data stored in the Launch configuration EBS is securely encrypted at rest
  - CKV_AWS_135  # Ensure that EC2 is EBS optimized
  - CKV_AWS_126  # Ensure that detailed monitoring is enabled for EC2 instances
  - CKV2_AWS_5   # Ensure that Security Groups are attached to another resource
  - CKV_AWS_23   # Ensure every security groups rule has a description
  - CKV_AWS_25   # Ensure no security groups allow ingress from 0.0.0.0:0 to port 80
  - CKV_AWS_24   # Ensure no security groups allow ingress from 0.0.0.0:0 to port 22

# Custom severity levels
severity:
  HIGH: error
  MEDIUM: warning
  LOW: info

# Output format
output: cli